# Build and autotest script for MatrixPilot firmware
# http://travis-ci.org

language: c

sudo: true

addons:
  apt:
    packages:
    - libc6:i386
    - libx11-6:i386
    - libxext6:i386
    - libstdc++6:i386
    - libexpat1:i386

before_install:
- chmod +x travis-install-dependencies.sh

install:
- ./travis-install-dependencies.sh
- export PATH=$PATH:/opt/microchip/xc16/v1.26/bin
- xc16-gcc --version

before_script:
- pwd
- ls -la

script:
- mkdir -p ./build-yml; cd ./build-yml
- mkdir -p ./SIL; cd ./SIL
- make -j 8 -f ../../makefile TARGET_NAME=MPSIM DEVICE=SIL
- cd ..; mkdir -p ./AUAV3; cd ./AUAV3
- make -j 8 -f ../../makefile TARGET_NAME=MatrixPilot DEVICE=AUAV3
- cd ..; mkdir -p ./UDB5; cd ./UDB5
- make -j 8 -f ../../makefile TARGET_NAME=MatrixPilot DEVICE=UDB5
- cd ..; mkdir -p ./UDB4; cd ./UDB4
- make -j 8 -f ../../makefile TARGET_NAME=MatrixPilot DEVICE=UDB4
- cd ../..
- pwd
- export PATH=/opt/microchip/xc16/v1.26/bin:$PATH
- xc16-gcc --version
- ./build-all.sh

after_success:
- find build | grep hex
- find build | grep map
- find build | grep out
- cd ~
